---
title: "Writing Functions"
author: "Vanessa Dinh"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

set.seed(1)
```

## Z-scores

Let's compute the z-score version of a list of numbers

```{r}
x_vec = rnorm(25, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Suppose you want to do this often -> make a function

```{r}
z_scores = function(x) {
  
  if(!is.numeric(x)) {
    stop("Z scores only work for numbers")
  }
  
  if(length(x) < 3) {
    stop("Z scores really only work if you have three or more numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  z
  
}

z_scores(x = x_vec)
```

```{r}
z_scores(3) # NA b/c can't take standard deviation of one number

z_scores("my name is jeff")

z_scores(x= 1:10)

z_scores(x = rbinom(1000, 1, .6))

z_scores(iris)

z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))

```

## Let's have multiple outputs

Get mean and sd from vector input

```{r}
mean_and_sd = function(x) {
  
  
   if(!is.numeric(x)) {
    stop("Z scores only work for numbers")
  }
  
  if(length(x) < 3) {
    stop("Z scores really only work if you have three or more numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}

mean_and_sd(x = x_vec)
mean_and_sd(x = 1:10)
mean_and_sd(x = rbinom(1000, 1, .5))


```

## Let's start with simulations

```{r}
x_vec = rnorm(n = 25, mean = 17, sd = 4)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
```

Do the same thing with a function w/ set default values

```{r}
sim_mean_sd = function(n_obs, true_mean = 7, true_sd = 4) {
  
  x = rnorm(n = n_obs, mean = true_mean, sd = true_sd)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
}
```
does it work?

```{r}
sim_mean_sd(n_obs = 25, true_mean = 100, true_sd = 1)
sim_mean_sd(2500, 10, 7) #if don't name arguments, assumes in order
```

## Fixing bad stuff


```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

Let's write a function to get reviews

```{r}
read_page_reviews = function(url){
  
  dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim() %>% 
    str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)

reviews = 
  tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
  )

reviews
}
```

Try with URL

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=2"

read_page_reviews(url)
```

What good does this do?

```{r}
base_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_url = str_c(base_url, c(1, 2, 4, 5))

dynamite_reviews =
  bind_rows(
  read_page_reviews(vec_url[1]),
  read_page_reviews(vec_url[2]),
  read_page_reviews(vec_url[3]),
  read_page_reviews(vec_url[4])
)
```

```{r}
lotr_load_and_tidy = function(path, range, movie_name) {
  
  df = readxl::read_excel(path, range = range) %>%
    janitor::clean_names() %>%
    gather(key = sex, value = words, female:male) %>%
    mutate(race = str_to_lower(race),
           movie = movie_name)
  
  df
  
}

lotr_tidy = 
  bind_rows(
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "B3:D6", "fellowship_ring"),
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "F3:H6", "two_towers"),
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "J3:L6", "return_king")) %>%
  select(movie, everything()) 
```

